### ISSUE TITLE
[PE-D] Finding inventory based on quantity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-2/tp#201]
When finding which items fall within a specific quantity range, the current implementation works quite well. One thing I would like to comment on is that when the user enters the command `find-i iqf/0  iqt/5000 iu/g`, the user may be wanting to find only those items in the inventory that have their unit between 0 and 5000 g (i.e. 0-5000 grams). However, this gives the following output: 

![image.png](https://raw.githubusercontent.com/loose-bus-change/ped/main/files/2bb89004-eae4-4b00-999e-7837bc002d93.png)

The user may not be looking to find items of the other units. While I understand the current implementation from a coding perspective, it may not be so evident to the user if they are looking to find all items that have a weight between x and y grams (assuming that they have entered 'g' for the unit, which is an acceptable input as it is widely used). Therefore, you could consider changing how this part of the find feature works, the rest of it is excellent! 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: loose-bus-change/ped#4

**Comment by zognin** [comment]
This is a matter of preference.
